[tool.poetry]
name = "blog-static"
version = "0.1.0"
description = ""
authors = ["Evan Savage <savage.evan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytz = "^2024.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
